spring:
  config:
    import: optional:file:./.env[.properties]

  application:
    name: multi-drive-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}

  servlet:
    multipart:
      max-file-size: ${APP_MAX_UPLOAD_SIZE:2GB}
      max-request-size: ${APP_MAX_UPLOAD_REQUEST_SIZE:3GB}
      file-size-threshold: ${APP_UPLOAD_FILE_SIZE_THRESHOLD:2MB}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

google:
  oauth2:
    drive-redirect-uri: ${GOOGLE_DRIVE_REDIRECT_URI}

  drive:
    webhook-url: ${GOOGLE_DRIVE_WEBHOOK_URL:}

app:
  security:
    token-encryption-key: ${TOKEN_ENCRYPTION_KEY}
